In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score ,confusion_matrix

In [2]:
df=pd.read_csv("Purchased_Dataset.csv")

In [3]:
df[df['Purchased']==1].head()

User ID  Gender  Age  EstimatedSalary  Purchased
7   15694829  Female   32           150000          1
16  15733883    Male   47            25000          1
17  15617482    Male   45            26000          1
18  15704583    Male   46            28000          1
19  15621083  Female   48            29000          1

In [4]:
x=df[["Age","EstimatedSalary"]]
y=df["Purchased"]

In [5]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [6]:
from sklearn.svm import SVC
svc=SVC(kernel='rbf')
svc.fit(x_train,y_train)
predict=svc.predict(x_test)
print("Accuracy score for SVC",accuracy_score(y_test,predict))
print(confusion_matrix(y_test,predict))
from sklearn.tree import DecisionTreeClassifier
tree=DecisionTreeClassifier()
tree.fit(x_train,y_train)
predict1=tree.predict(x_test)
print("Accuracy score for Decision tree classiifier",accuracy_score(y_test,predict1))
print(confusion_matrix(y_test,predict1))


Accuracy score for SVC 0.825
[[56  2]
 [12 10]]
Accuracy score for Decision tree classiifier 0.9
[[53  5]
 [ 3 19]]


In [8]:
from sklearn.ensemble import RandomForestClassifier
forest=RandomForestClassifier(n_estimators=100)
forest.fit(x_train,y_train)
predict2=forest.predict(x_test)
print("Accuracy score for Random forest",accuracy_score(y_test,predict2))


Accuracy score for Random forest 0.9125


In [9]:
from sklearn.model_selection import cross_val_score
cross_val_score(tree,x,y,cv=10).mean()

0.8375

In [10]:
def get_score(model,x,y):
    return(cross_val_score(model,x,y,cv=10).mean())

In [11]:
get_score(forest,x,y)


0.8724999999999999

In [12]:
get_score(forest,x,y)

0.8775000000000001

In [13]:
get_score(svc,x,y)

0.7725000000000001

In [18]:
tree.predict([[3,200000]])

array([0], dtype=int64)